//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WTGWizard.Main.Language {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WTGWizard.Main.Language.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Tasks 的本地化字符串。
        /// </summary>
        public static string App_NavTabTask_Content {
            get {
                return ResourceManager.GetString("App.NavTabTask.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome 的本地化字符串。
        /// </summary>
        public static string App_NavTabWelcome_Content {
            get {
                return ResourceManager.GetString("App.NavTabWelcome.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wizard 的本地化字符串。
        /// </summary>
        public static string App_NavTabWizard_Content {
            get {
                return ResourceManager.GetString("App.NavTabWizard.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Make sure you select the correct disk for deployment to avoid accidental data loss! 的本地化字符串。
        /// </summary>
        public static string InfoBar_DataSecurity_Message {
            get {
                return ResourceManager.GetString("InfoBar.DataSecurity.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Security Warning 的本地化字符串。
        /// </summary>
        public static string InfoBar_DataSecurity_Title {
            get {
                return ResourceManager.GetString("InfoBar.DataSecurity.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image Verification Failed! 的本地化字符串。
        /// </summary>
        public static string InfoBar_ImageVerificationFailed_Title {
            get {
                return ResourceManager.GetString("InfoBar.ImageVerificationFailed.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selected disk has no ESP partition. Only Clean Install available. 的本地化字符串。
        /// </summary>
        public static string InfoBar_NoEsp_Message {
            get {
                return ResourceManager.GetString("InfoBar.NoEsp.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No ESP Partition 的本地化字符串。
        /// </summary>
        public static string InfoBar_NoEsp_Title {
            get {
                return ResourceManager.GetString("InfoBar.NoEsp.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open diskmgmt.msc 的本地化字符串。
        /// </summary>
        public static string InfoBar_PartNoLetter_ActionBtn {
            get {
                return ResourceManager.GetString("InfoBar.PartNoLetter.ActionBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selected partition has no drive letter assigned, deployment cannot proceed. Please assign a drive letter in Disk Management. 的本地化字符串。
        /// </summary>
        public static string InfoBar_PartNoLetter_Message {
            get {
                return ResourceManager.GetString("InfoBar.PartNoLetter.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Drive Letter 的本地化字符串。
        /// </summary>
        public static string InfoBar_PartNoLetter_Title {
            get {
                return ResourceManager.GetString("InfoBar.PartNoLetter.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reserved partition is enabled but capacity is 0. Please adjust partition size. 的本地化字符串。
        /// </summary>
        public static string InfoBar_ReservedSizeZero_Message {
            get {
                return ResourceManager.GetString("InfoBar.ReservedSizeZero.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reserved Partition Size is 0 的本地化字符串。
        /// </summary>
        public static string InfoBar_ReservedSizeZero_Title {
            get {
                return ResourceManager.GetString("InfoBar.ReservedSizeZero.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Abort 的本地化字符串。
        /// </summary>
        public static string Page_Task_AbortButton {
            get {
                return ResourceManager.GetString("Page.Task.AbortButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disk Busy 的本地化字符串。
        /// </summary>
        public static string Page_Task_DiskPerf_BusyLabel {
            get {
                return ResourceManager.GetString("Page.Task.DiskPerf.BusyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disk # 的本地化字符串。
        /// </summary>
        public static string Page_Task_DiskPerf_NumberLabel {
            get {
                return ResourceManager.GetString("Page.Task.DiskPerf.NumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read 的本地化字符串。
        /// </summary>
        public static string Page_Task_DiskPerf_ReadLabel {
            get {
                return ResourceManager.GetString("Page.Task.DiskPerf.ReadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Write 的本地化字符串。
        /// </summary>
        public static string Page_Task_DiskPerf_WriteLabel {
            get {
                return ResourceManager.GetString("Page.Task.DiskPerf.WriteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Freeze Output 的本地化字符串。
        /// </summary>
        public static string Page_Task_FreezeToggle {
            get {
                return ResourceManager.GetString("Page.Task.FreezeToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Word Wrap 的本地化字符串。
        /// </summary>
        public static string Page_Task_WrapToggle {
            get {
                return ResourceManager.GetString("Page.Task.WrapToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Try it now! 的本地化字符串。
        /// </summary>
        public static string Page_Welcome_GoWizard_Content {
            get {
                return ResourceManager.GetString("Page.Welcome.GoWizard.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WTGWizard will guide you step by step through the process of creating your Windows To Go workstation! 的本地化字符串。
        /// </summary>
        public static string Page_Welcome_WelcomeMsg_Text {
            get {
                return ResourceManager.GetString("Page.Welcome.WelcomeMsg.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome to WTGWizard👋 的本地化字符串。
        /// </summary>
        public static string Page_Welcome_WelcomeTitle_Text {
            get {
                return ResourceManager.GetString("Page.Welcome.WelcomeTitle.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back 的本地化字符串。
        /// </summary>
        public static string Page_WizHost_BackButton_Content {
            get {
                return ResourceManager.GetString("Page.WizHost.BackButton.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next 的本地化字符串。
        /// </summary>
        public static string Page_WizHost_ForwardButton_Content {
            get {
                return ResourceManager.GetString("Page.WizHost.ForwardButton.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicates whether the current image contains an answer file.
        ///Found path: {0} 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_AdvOptions_AnsFile_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.AdvOptions.AnsFile.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Found {0} answer file(s) in the image 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_AdvOptions_AnsFile_Found {
            get {
                return ResourceManager.GetString("Page.WizStep.AdvOptions.AnsFile.Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In-image Answer File! 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_AdvOptions_AnsFile_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.AdvOptions.AnsFile.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current image already contains an answer file. Importing a new answer file will overwrite the existing configuration.
        ///Enable &quot;Clear in-image answer files&quot; option if you want to use a new answer file. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_AdvOptions_AnsFile_InfoBar {
            get {
                return ResourceManager.GetString("Page.WizStep.AdvOptions.AnsFile.InfoBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No image file selected 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_AdvOptions_AnsFile_NoImage {
            get {
                return ResourceManager.GetString("Page.WizStep.AdvOptions.AnsFile.NoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_AdvOptions_AnsFile_None {
            get {
                return ResourceManager.GetString("Page.WizStep.AdvOptions.AnsFile.None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No answer file found in the image 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_AdvOptions_AnsFile_NotFound {
            get {
                return ResourceManager.GetString("Page.WizStep.AdvOptions.AnsFile.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Answer File Settings 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_AdvOptions_AnsFileGroup {
            get {
                return ResourceManager.GetString("Page.WizStep.AdvOptions.AnsFileGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No answer file has been selected. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_AdvOptions_AnsFilePath_Placeholder {
            get {
                return ResourceManager.GetString("Page.WizStep.AdvOptions.AnsFilePath.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 bcdboot Settings 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_AdvOptions_BCDBootGroup {
            get {
                return ResourceManager.GetString("Page.WizStep.AdvOptions.BCDBootGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use the CA 2023-signed boot binaries for boot creation.
        ///This setting is available only on Windows 11 version 26100.8037 and later. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_AdvOptions_BootEx_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.AdvOptions.BootEx.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use updated boot binaries 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_AdvOptions_BootEx_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.AdvOptions.BootEx.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable verbose logging for bcdboot. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_AdvOptions_BootVerbose_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.AdvOptions.BootVerbose.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use verbose logging 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_AdvOptions_BootVerbose_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.AdvOptions.BootVerbose.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear in-image answer files before importing. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_AdvOptions_CleanAnsFile_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.AdvOptions.CleanAnsFile.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear in-image answer files 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_AdvOptions_CleanAnsFile_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.AdvOptions.CleanAnsFile.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import a new unattend file to apply. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_AdvOptions_CustomAnsFile_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.AdvOptions.CustomAnsFile.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use a new answer file 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_AdvOptions_CustomAnsFile_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.AdvOptions.CustomAnsFile.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configure driver integration, answer file, and boot options. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_AdvOptions_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.AdvOptions.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Integrate drivers into Windows To Go. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_AdvOptions_DriverEnabled_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.AdvOptions.DriverEnabled.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Integrate drivers 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_AdvOptions_DriverEnabled_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.AdvOptions.DriverEnabled.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drivers Integration 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_AdvOptions_DriverGroup {
            get {
                return ResourceManager.GetString("Page.WizStep.AdvOptions.DriverGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select the location of the driver. You can choose it using the Folder Picker or enter it manually. 
        ///Incorrect drivers path will lead to a failure of deployment. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_AdvOptions_DriverPath_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.AdvOptions.DriverPath.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drivers location 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_AdvOptions_DriverPath_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.AdvOptions.DriverPath.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No drivers path has been selected. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_AdvOptions_DriverPath_Placeholder {
            get {
                return ResourceManager.GetString("Page.WizStep.AdvOptions.DriverPath.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extract 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_AdvOptions_Extract_CommitText {
            get {
                return ResourceManager.GetString("Page.WizStep.AdvOptions.Extract.CommitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extract 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_AdvOptions_ExtractAnsFile_Button {
            get {
                return ResourceManager.GetString("Page.WizStep.AdvOptions.ExtractAnsFile.Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extract the answer file from the current image index. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_AdvOptions_ExtractAnsFile_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.AdvOptions.ExtractAnsFile.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extract answer file 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_AdvOptions_ExtractAnsFile_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.AdvOptions.ExtractAnsFile.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allow the integration of unsigned drivers 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_AdvOptions_ForceUnsigned_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.AdvOptions.ForceUnsigned.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allow unsigned drivers 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_AdvOptions_ForceUnsigned_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.AdvOptions.ForceUnsigned.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select an answer file to apply. Using an incorrect answer file will cause Windows To Go to fail during initialization. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_AdvOptions_SelectAnsFile_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.AdvOptions.SelectAnsFile.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select an answer file 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_AdvOptions_SelectAnsFile_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.AdvOptions.SelectAnsFile.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Advanced Options 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_AdvOptions_Title {
            get {
                return ResourceManager.GetString("Page.WizStep.AdvOptions.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Advanced Settings 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_Confirm_AdvancedGroup {
            get {
                return ResourceManager.GetString("Page.WizStep.Confirm.AdvancedGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Answer File Location 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_Confirm_AnswerFilePath_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.Confirm.AnswerFilePath.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Updated Boot File Binaries 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_Confirm_BootEx_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.Confirm.BootEx.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 bcdboot Verbose Output 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_Confirm_BootVerbose_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.Confirm.BootVerbose.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clean Up Answer File in Image 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_Confirm_CleanAnsFile_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.Confirm.CleanAnsFile.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_Confirm_DeployDialog_CloseButtonText {
            get {
                return ResourceManager.GetString("Page.WizStep.Confirm.DeployDialog.CloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Once started, the task cannot be actively terminated! 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_Confirm_DeployDialog_ContentText {
            get {
                return ResourceManager.GetString("Page.WizStep.Confirm.DeployDialog.ContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_Confirm_DeployDialog_PrimaryButtonText {
            get {
                return ResourceManager.GetString("Page.WizStep.Confirm.DeployDialog.PrimaryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start deployment now? 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_Confirm_DeployDialog_Title {
            get {
                return ResourceManager.GetString("Page.WizStep.Confirm.DeployDialog.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deployment Method 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_Confirm_DeployMethodGroup {
            get {
                return ResourceManager.GetString("Page.WizStep.Confirm.DeployMethodGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deployment Options 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_Confirm_DeployOptionsGroup {
            get {
                return ResourceManager.GetString("Page.WizStep.Confirm.DeployOptionsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Review deployment configuration summary, then start deployment. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_Confirm_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.Confirm.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Integrate Drivers 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_Confirm_DriversIntegration_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.Confirm.DriversIntegration.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Driver Path 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_Confirm_DriversPath_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.Confirm.DriversPath.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ESP partition size 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_Confirm_EspSize_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.Confirm.EspSize.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide Local Disks 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_Confirm_HideLocalDisks_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.Confirm.HideLocalDisks.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image Information 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_Confirm_ImageInfoGroup {
            get {
                return ResourceManager.GetString("Page.WizStep.Confirm.ImageInfoGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import Answer File 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_Confirm_ImportAnswerFile_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.Confirm.ImportAnswerFile.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clean Install 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_Confirm_MethodType_Clean {
            get {
                return ResourceManager.GetString("Page.WizStep.Confirm.MethodType.Clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deployment method 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_Confirm_MethodType_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.Confirm.MethodType.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Install to Partition 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_Confirm_MethodType_Partition {
            get {
                return ResourceManager.GetString("Page.WizStep.Confirm.MethodType.Partition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Default Drive Letter 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_Confirm_NoDefaultDriveLetter_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.Confirm.NoDefaultDriveLetter.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OS volume label 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_Confirm_OsLabel_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.Confirm.OsLabel.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto (Use All Space) 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_Confirm_OsSize_Auto {
            get {
                return ResourceManager.GetString("Page.WizStep.Confirm.OsSize.Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OS partition size 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_Confirm_OsSize_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.Confirm.OsSize.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Partition Layout 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_Confirm_PartitionConfig_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.Confirm.PartitionConfig.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prevent Device Encryption 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_Confirm_PreventEncryption_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.Confirm.PreventEncryption.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove OS Drive Letter 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_Confirm_RemoveOsDriveLetter_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.Confirm.RemoveOsDriveLetter.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reserved partition file system 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_Confirm_ReservedVolFs_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.Confirm.ReservedVolFs.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reserved partition label 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_Confirm_ReservedVolLabel_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.Confirm.ReservedVolLabel.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reserved partition size 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_Confirm_ReservedVolSize_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.Confirm.ReservedVolSize.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 After confirming that all settings are correct, click the &quot;Start Deployment&quot; button to begin deployment. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_Confirm_StartDeploy_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.Confirm.StartDeploy.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Deployment 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_Confirm_StartDeploy_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.Confirm.StartDeploy.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Deployment 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_Confirm_StartDeployButton {
            get {
                return ResourceManager.GetString("Page.WizStep.Confirm.StartDeployButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Deployment 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_Confirm_StartDeployGroup {
            get {
                return ResourceManager.GetString("Page.WizStep.Confirm.StartDeployGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target Disk 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_Confirm_TargetDisk_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.Confirm.TargetDisk.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target Partition 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_Confirm_TargetPartition_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.Confirm.TargetPartition.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_Confirm_Title {
            get {
                return ResourceManager.GetString("Page.WizStep.Confirm.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import Unsigned Drivers 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_Confirm_UnsignedDrivers_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.Confirm.UnsignedDrivers.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deploy Windows using DISM 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_Confirm_UseDismToDeploy_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.Confirm.UseDismToDeploy.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clean Install 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_CleanInstall {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.CleanInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select disk and deployment method. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set the capacity of the ESP partition. It should be between 300MB and 500MB. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_EspSize_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.EspSize.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ESP Partition Capacity 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_EspSize_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.EspSize.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose whether to perform a clean installation or install to a specific partition. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_Method_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.Method.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deployment Method 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_Method_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.Method.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set the volume label for the OS partition. If left blank, &apos;OS&apos; will be used as the volume label. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_OsLabel_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.OsLabel.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OS Partition Label 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_OsLabel_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.OsLabel.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set the capacity of the system partition; the minimum value is the size of the expanded image. If no reserved partition is specified, use all remaining space. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_OsSize_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.OsSize.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OS Partition Capacity 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_OsSize_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.OsSize.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configure the disk layout and partition sizes for clean installation. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_PartConfig_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.PartConfig.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configure Disk Layout 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_PartConfig_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.PartConfig.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Partition Install 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_PartInstall {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.PartInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set the volume label for the OS partition. If left blank, &apos;OS&apos; will be used as the volume label. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_PartOsLabel_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.PartOsLabel.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OS Partition Label 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_PartOsLabel_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.PartOsLabel.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create an additional reserved volume after the OS partition for other purposes. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_Reserved_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.Reserved.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Reserved Partition 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_Reserved_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.Reserved.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set the file system for the reserved partition. NTFS is recommended for external hard drives. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_ReservedFs_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.ReservedFs.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reserved Partition File System 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_ReservedFs_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.ReservedFs.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set the volume label for the Reserved partition. If left blank, &apos;Reserved&apos; will be used as the volume label. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_ReservedLabel_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.ReservedLabel.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reserved Partition Label 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_ReservedLabel_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.ReservedLabel.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 e.g. Reserved 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_ReservedLabel_Placeholder {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.ReservedLabel.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set the capacity of the reserved partition. It is automatically calculated based on the remaining space. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_ReservedSize_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.ReservedSize.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reserved Partition Capacity 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_ReservedSize_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.ReservedSize.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select the external hard drive or removable drive on which you want to install Windows To Go. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_SelDisk_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.SelDisk.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Disk 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_SelDisk_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.SelDisk.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a disk 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_SelDisk_Placeholder {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.SelDisk.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select the partition to deploy Windows To Go. All the data on the selected partition will be erased. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_SelPart_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.SelPart.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Install to Partition 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_SelPart_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.SelPart.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a partition 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_SelPart_Placeholder {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.SelPart.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deploy Method 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_Title {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deployment Settings 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployOptions_DeployGroup {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployOptions.DeployGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configure Windows To Go settings and deploy. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployOptions_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployOptions.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disk Settings 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployOptions_DiskGroup {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployOptions.DiskGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 After Windows To Go has booted, keep the internal hard drives offline to prevent data loss. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployOptions_HideLocalDisks_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployOptions.HideLocalDisks.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keep internal hard drives offline 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployOptions_HideLocalDisks_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployOptions.HideLocalDisks.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prevent Windows from assigning a drive letter to the OS partition to avoid accidentally damaging Windows To Go. 
        ///This setting is only available for external hard disks. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployOptions_NoDefaultDriveLetter_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployOptions.NoDefaultDriveLetter.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Don&apos;t assign drive letter for OS partition 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployOptions_NoDefaultDriveLetter_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployOptions.NoDefaultDriveLetter.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prevent BitLocker device encryption from running automatically after Windows is initialized on eligible devices. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployOptions_PreventDeviceEncryption_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployOptions.PreventDeviceEncryption.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prevent device encryption 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployOptions_PreventDeviceEncryption_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployOptions.PreventDeviceEncryption.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Once deployment is complete, remove the drive letter for the OS partition. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployOptions_RemoveOsDriveLetter_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployOptions.RemoveOsDriveLetter.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove OS partition drive letter 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployOptions_RemoveOsDriveLetter_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployOptions.RemoveOsDriveLetter.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deploy Options 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployOptions_Title {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployOptions.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deploy Windows using DISM instead of wimlib. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployOptions_UseDism_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployOptions.UseDism.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deploy Windows using DISM 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployOptions_UseDism_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployOptions.UseDism.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows To Go Settings 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployOptions_WTGGroup {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployOptions.WTGGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a WIM/ESD image file and choose the image index to deploy. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_ImageConfig_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.ImageConfig.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No image file has been selected. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_ImageConfig_FilePathPlaceholder {
            get {
                return ResourceManager.GetString("Page.WizStep.ImageConfig.FilePathPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a index 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_ImageConfig_IdxCombo_Placeholder {
            get {
                return ResourceManager.GetString("Page.WizStep.ImageConfig.IdxCombo.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image Information 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_ImageConfig_InfoCardHeader {
            get {
                return ResourceManager.GetString("Page.WizStep.ImageConfig.InfoCardHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select the image index to deploy. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_ImageConfig_SelIdx_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.ImageConfig.SelIdx.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Image Index 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_ImageConfig_SelIdx_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.ImageConfig.SelIdx.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Supports .wim and .esd; use the file picker to choose an image 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_ImageConfig_SelImg_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.ImageConfig.SelImg.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Image File 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_ImageConfig_SelImg_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.ImageConfig.SelImg.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image Configuration 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_ImageConfig_SelImgGroup {
            get {
                return ResourceManager.GetString("Page.WizStep.ImageConfig.SelImgGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image Config 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_ImageConfig_Title {
            get {
                return ResourceManager.GetString("Page.WizStep.ImageConfig.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply Windows To Go settings 的本地化字符串。
        /// </summary>
        public static string Task_ApplySysSettings_Desc {
            get {
                return ResourceManager.GetString("Task.ApplySysSettings.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply Windows settings 的本地化字符串。
        /// </summary>
        public static string Task_ApplySysSettings_Title {
            get {
                return ResourceManager.GetString("Task.ApplySysSettings.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Windows boot files. 的本地化字符串。
        /// </summary>
        public static string Task_CreateBootFiles_Desc {
            get {
                return ResourceManager.GetString("Task.CreateBootFiles.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create boot files 的本地化字符串。
        /// </summary>
        public static string Task_CreateBootFiles_Title {
            get {
                return ResourceManager.GetString("Task.CreateBootFiles.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create EFI system partition and primary partition 的本地化字符串。
        /// </summary>
        public static string Task_CreateDiskLayout_Desc {
            get {
                return ResourceManager.GetString("Task.CreateDiskLayout.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create disk layout 的本地化字符串。
        /// </summary>
        public static string Task_CreateDiskLayout_Title {
            get {
                return ResourceManager.GetString("Task.CreateDiskLayout.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extract Windows image to target partition. 的本地化字符串。
        /// </summary>
        public static string Task_ExtractImage_Desc {
            get {
                return ResourceManager.GetString("Task.ExtractImage.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extract image 的本地化字符串。
        /// </summary>
        public static string Task_ExtractImage_Title {
            get {
                return ResourceManager.GetString("Task.ExtractImage.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import new answer file. 的本地化字符串。
        /// </summary>
        public static string Task_ImportAnswerFile_Desc {
            get {
                return ResourceManager.GetString("Task.ImportAnswerFile.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import answer file 的本地化字符串。
        /// </summary>
        public static string Task_ImportAnswerFile_Title {
            get {
                return ResourceManager.GetString("Task.ImportAnswerFile.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Integrate drivers into Windows. 的本地化字符串。
        /// </summary>
        public static string Task_IntegrateDrivers_Desc {
            get {
                return ResourceManager.GetString("Task.IntegrateDrivers.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Integrate drivers 的本地化字符串。
        /// </summary>
        public static string Task_IntegrateDrivers_Title {
            get {
                return ResourceManager.GetString("Task.IntegrateDrivers.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove ESP drive letter. 的本地化字符串。
        /// </summary>
        public static string Task_RemoveDriveLetters_Desc_Esp {
            get {
                return ResourceManager.GetString("Task.RemoveDriveLetters.Desc.Esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove ESP and OS drive letters. 的本地化字符串。
        /// </summary>
        public static string Task_RemoveDriveLetters_Desc_EspOs {
            get {
                return ResourceManager.GetString("Task.RemoveDriveLetters.Desc.EspOs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove drive letters 的本地化字符串。
        /// </summary>
        public static string Task_RemoveDriveLetters_Title {
            get {
                return ResourceManager.GetString("Task.RemoveDriveLetters.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Architecture: 的本地化字符串。
        /// </summary>
        public static string UsrCtrl_ImageInfoCard_ArchLabel {
            get {
                return ResourceManager.GetString("UsrCtrl.ImageInfoCard.ArchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Build: 的本地化字符串。
        /// </summary>
        public static string UsrCtrl_ImageInfoCard_BuildLabel {
            get {
                return ResourceManager.GetString("UsrCtrl.ImageInfoCard.BuildLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date Created: 的本地化字符串。
        /// </summary>
        public static string UsrCtrl_ImageInfoCard_DateLabel {
            get {
                return ResourceManager.GetString("UsrCtrl.ImageInfoCard.DateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description: 的本地化字符串。
        /// </summary>
        public static string UsrCtrl_ImageInfoCard_DescLabel {
            get {
                return ResourceManager.GetString("UsrCtrl.ImageInfoCard.DescLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display Description: 的本地化字符串。
        /// </summary>
        public static string UsrCtrl_ImageInfoCard_DispDescLabel {
            get {
                return ResourceManager.GetString("UsrCtrl.ImageInfoCard.DispDescLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Feature Update: 的本地化字符串。
        /// </summary>
        public static string UsrCtrl_ImageInfoCard_FeatureLabel {
            get {
                return ResourceManager.GetString("UsrCtrl.ImageInfoCard.FeatureLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Index: 的本地化字符串。
        /// </summary>
        public static string UsrCtrl_ImageInfoCard_IndexLabel {
            get {
                return ResourceManager.GetString("UsrCtrl.ImageInfoCard.IndexLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading image info... 的本地化字符串。
        /// </summary>
        public static string UsrCtrl_ImageInfoCard_Loading {
            get {
                return ResourceManager.GetString("UsrCtrl.ImageInfoCard.Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows Logo 的本地化字符串。
        /// </summary>
        public static string UsrCtrl_ImageInfoCard_Logo {
            get {
                return ResourceManager.GetString("UsrCtrl.ImageInfoCard.Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name: 的本地化字符串。
        /// </summary>
        public static string UsrCtrl_ImageInfoCard_NameLabel {
            get {
                return ResourceManager.GetString("UsrCtrl.ImageInfoCard.NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expanded Size: 的本地化字符串。
        /// </summary>
        public static string UsrCtrl_ImageInfoCard_SizeLabel {
            get {
                return ResourceManager.GetString("UsrCtrl.ImageInfoCard.SizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version: 的本地化字符串。
        /// </summary>
        public static string UsrCtrl_ImageInfoCard_VersionLabel {
            get {
                return ResourceManager.GetString("UsrCtrl.ImageInfoCard.VersionLabel", resourceCulture);
            }
        }
    }
}
