//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WTGWizard.Main.Language {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WTGWizard.Main.Language.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Tasks 的本地化字符串。
        /// </summary>
        public static string App_NavTabTask_Content {
            get {
                return ResourceManager.GetString("App.NavTabTask.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome 的本地化字符串。
        /// </summary>
        public static string App_NavTabWelcome_Content {
            get {
                return ResourceManager.GetString("App.NavTabWelcome.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wizard 的本地化字符串。
        /// </summary>
        public static string App_NavTabWizard_Content {
            get {
                return ResourceManager.GetString("App.NavTabWizard.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Make sure you select the correct disk for deployment to avoid accidental data loss! 的本地化字符串。
        /// </summary>
        public static string InfoBar_DataSecurity_Message {
            get {
                return ResourceManager.GetString("InfoBar.DataSecurity.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Security Warning 的本地化字符串。
        /// </summary>
        public static string InfoBar_DataSecurity_Title {
            get {
                return ResourceManager.GetString("InfoBar.DataSecurity.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image Verification Failed! 的本地化字符串。
        /// </summary>
        public static string InfoBar_ImageVerificationFailed_Title {
            get {
                return ResourceManager.GetString("InfoBar.ImageVerificationFailed.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selected disk has no ESP partition. Only Clean Install available. 的本地化字符串。
        /// </summary>
        public static string InfoBar_NoEsp_Message {
            get {
                return ResourceManager.GetString("InfoBar.NoEsp.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No ESP Partition 的本地化字符串。
        /// </summary>
        public static string InfoBar_NoEsp_Title {
            get {
                return ResourceManager.GetString("InfoBar.NoEsp.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open diskmgmt.msc 的本地化字符串。
        /// </summary>
        public static string InfoBar_PartNoLetter_ActionBtn {
            get {
                return ResourceManager.GetString("InfoBar.PartNoLetter.ActionBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selected partition has no drive letter assigned, deployment cannot proceed. Please assign a drive letter in Disk Management. 的本地化字符串。
        /// </summary>
        public static string InfoBar_PartNoLetter_Message {
            get {
                return ResourceManager.GetString("InfoBar.PartNoLetter.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Drive Letter 的本地化字符串。
        /// </summary>
        public static string InfoBar_PartNoLetter_Title {
            get {
                return ResourceManager.GetString("InfoBar.PartNoLetter.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reserved partition is enabled but capacity is 0. Please adjust partition size. 的本地化字符串。
        /// </summary>
        public static string InfoBar_ReservedSizeZero_Message {
            get {
                return ResourceManager.GetString("InfoBar.ReservedSizeZero.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reserved Partition Size is 0 的本地化字符串。
        /// </summary>
        public static string InfoBar_ReservedSizeZero_Title {
            get {
                return ResourceManager.GetString("InfoBar.ReservedSizeZero.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Try it now! 的本地化字符串。
        /// </summary>
        public static string Page_Welcome_GoWizard_Content {
            get {
                return ResourceManager.GetString("Page.Welcome.GoWizard.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WTGWizard will guide you step by step through the process of creating your Windows To Go workstation! 的本地化字符串。
        /// </summary>
        public static string Page_Welcome_WelcomeMsg_Text {
            get {
                return ResourceManager.GetString("Page.Welcome.WelcomeMsg.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome to WTGWizard👋 的本地化字符串。
        /// </summary>
        public static string Page_Welcome_WelcomeTitle_Text {
            get {
                return ResourceManager.GetString("Page.Welcome.WelcomeTitle.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back 的本地化字符串。
        /// </summary>
        public static string Page_WizHost_BackButton_Content {
            get {
                return ResourceManager.GetString("Page.WizHost.BackButton.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next 的本地化字符串。
        /// </summary>
        public static string Page_WizHost_ForwardButton_Content {
            get {
                return ResourceManager.GetString("Page.WizHost.ForwardButton.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clean Install 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_CleanInstall {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.CleanInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select disk and deployment method. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set the capacity of the ESP partition. It should be between 300MB and 500MB. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_EspSize_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.EspSize.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ESP Partition Capacity 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_EspSize_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.EspSize.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose whether to perform a clean installation or install to a specific partition. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_Method_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.Method.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deployment Method 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_Method_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.Method.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set the volume label for the OS partition. If left blank, &apos;OS&apos; will be used as the volume label. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_OsLabel_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.OsLabel.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OS Partition Label 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_OsLabel_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.OsLabel.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set the capacity of the system partition; the minimum value is the size of the expanded image. If no reserved partition is specified, use all remaining space. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_OsSize_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.OsSize.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OS Partition Capacity 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_OsSize_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.OsSize.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configure the disk layout and partition sizes for clean installation. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_PartConfig_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.PartConfig.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configure Disk Layout 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_PartConfig_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.PartConfig.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Partition Install 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_PartInstall {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.PartInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set the volume label for the OS partition. If left blank, &apos;OS&apos; will be used as the volume label. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_PartOsLabel_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.PartOsLabel.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OS Partition Label 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_PartOsLabel_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.PartOsLabel.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create an additional reserved volume after the OS partition for other purposes. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_Reserved_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.Reserved.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Reserved Partition 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_Reserved_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.Reserved.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set the file system for the reserved partition. NTFS is recommended for external hard drives. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_ReservedFs_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.ReservedFs.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reserved Partition File System 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_ReservedFs_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.ReservedFs.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set the volume label for the Reserved partition. If left blank, &apos;Reserved&apos; will be used as the volume label. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_ReservedLabel_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.ReservedLabel.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reserved Partition Label 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_ReservedLabel_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.ReservedLabel.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 e.g. Reserved 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_ReservedLabel_Placeholder {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.ReservedLabel.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set the capacity of the reserved partition. It is automatically calculated based on the remaining space. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_ReservedSize_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.ReservedSize.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reserved Partition Capacity 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_ReservedSize_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.ReservedSize.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select the external hard drive or removable drive on which you want to install Windows To Go. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_SelDisk_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.SelDisk.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Disk 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_SelDisk_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.SelDisk.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a disk 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_SelDisk_Placeholder {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.SelDisk.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select the partition to deploy Windows To Go. All the data on the selected partition will be erased. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_SelPart_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.SelPart.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Install to Partition 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_SelPart_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.SelPart.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a partition 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_SelPart_Placeholder {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.SelPart.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deploy Method 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployMethod_Title {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployMethod.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deployment Settings 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployOptions_DeployGroup {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployOptions.DeployGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configure Windows To Go deployment options and disk settings. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployOptions_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployOptions.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disk Settings 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployOptions_DiskGroup {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployOptions.DiskGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 After Windows To Go has booted, keep the internal hard drives offline to prevent data loss. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployOptions_HideLocalDisks_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployOptions.HideLocalDisks_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keep internal hard drives offline 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployOptions_HideLocalDisks_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployOptions.HideLocalDisks_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prevent Windows from assigning a drive letter to the OS partition to avoid accidentally damaging Windows To Go. This setting is only available for external hard disks. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployOptions_NoDefaultDriveLetter_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployOptions.NoDefaultDriveLetter_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Don&apos;t assign drive letter for OS partition 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployOptions_NoDefaultDriveLetter_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployOptions.NoDefaultDriveLetter_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prevent BitLocker device encryption from running automatically after Windows To Go is initialized on eligible devices. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployOptions_PreventDeviceEncryption_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployOptions.PreventDeviceEncryption_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prevent device encryption 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployOptions_PreventDeviceEncryption_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployOptions.PreventDeviceEncryption_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Once deployment is complete, remove the drive letter for the OS partition. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployOptions_RemoveOsDriveLetter_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployOptions.RemoveOsDriveLetter_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove OS partition drive letter 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployOptions_RemoveOsDriveLetter_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployOptions.RemoveOsDriveLetter_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deploy Options 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployOptions_Title {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployOptions.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deploy Windows using DISM instead of wimlib. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployOptions_UseDism_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployOptions.UseDism_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deploy Windows using DISM 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployOptions_UseDism_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployOptions.UseDism_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows To Go Settings 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_DeployOptions_WTGGroup {
            get {
                return ResourceManager.GetString("Page.WizStep.DeployOptions.WTGGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a WIM/ESD image file and choose the image index to deploy. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_ImageConfig_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.ImageConfig.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No image file has been selected. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_ImageConfig_FilePathPlaceholder {
            get {
                return ResourceManager.GetString("Page.WizStep.ImageConfig.FilePathPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a index 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_ImageConfig_IdxCombo_Placeholder {
            get {
                return ResourceManager.GetString("Page.WizStep.ImageConfig.IdxCombo.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image Information 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_ImageConfig_InfoCardHeader {
            get {
                return ResourceManager.GetString("Page.WizStep.ImageConfig.InfoCardHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select the image index to deploy. 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_ImageConfig_SelIdx_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.ImageConfig.SelIdx.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Image Index 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_ImageConfig_SelIdx_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.ImageConfig.SelIdx.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Supports .wim and .esd; use the file picker to choose an image 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_ImageConfig_SelImg_Desc {
            get {
                return ResourceManager.GetString("Page.WizStep.ImageConfig.SelImg.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Image File 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_ImageConfig_SelImg_Header {
            get {
                return ResourceManager.GetString("Page.WizStep.ImageConfig.SelImg.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image Configuration 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_ImageConfig_SelImgGroup {
            get {
                return ResourceManager.GetString("Page.WizStep.ImageConfig.SelImgGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image Config 的本地化字符串。
        /// </summary>
        public static string Page_WizStep_ImageConfig_Title {
            get {
                return ResourceManager.GetString("Page.WizStep.ImageConfig.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Architecture: 的本地化字符串。
        /// </summary>
        public static string UsrCtrl_ImageInfoCard_ArchLabel {
            get {
                return ResourceManager.GetString("UsrCtrl.ImageInfoCard.ArchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Build: 的本地化字符串。
        /// </summary>
        public static string UsrCtrl_ImageInfoCard_BuildLabel {
            get {
                return ResourceManager.GetString("UsrCtrl.ImageInfoCard.BuildLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date Created: 的本地化字符串。
        /// </summary>
        public static string UsrCtrl_ImageInfoCard_DateLabel {
            get {
                return ResourceManager.GetString("UsrCtrl.ImageInfoCard.DateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description: 的本地化字符串。
        /// </summary>
        public static string UsrCtrl_ImageInfoCard_DescLabel {
            get {
                return ResourceManager.GetString("UsrCtrl.ImageInfoCard.DescLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display Description: 的本地化字符串。
        /// </summary>
        public static string UsrCtrl_ImageInfoCard_DispDescLabel {
            get {
                return ResourceManager.GetString("UsrCtrl.ImageInfoCard.DispDescLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Feature Update: 的本地化字符串。
        /// </summary>
        public static string UsrCtrl_ImageInfoCard_FeatureLabel {
            get {
                return ResourceManager.GetString("UsrCtrl.ImageInfoCard.FeatureLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Index: 的本地化字符串。
        /// </summary>
        public static string UsrCtrl_ImageInfoCard_IndexLabel {
            get {
                return ResourceManager.GetString("UsrCtrl.ImageInfoCard.IndexLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading image info... 的本地化字符串。
        /// </summary>
        public static string UsrCtrl_ImageInfoCard_Loading {
            get {
                return ResourceManager.GetString("UsrCtrl.ImageInfoCard.Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows Logo 的本地化字符串。
        /// </summary>
        public static string UsrCtrl_ImageInfoCard_Logo {
            get {
                return ResourceManager.GetString("UsrCtrl.ImageInfoCard.Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name: 的本地化字符串。
        /// </summary>
        public static string UsrCtrl_ImageInfoCard_NameLabel {
            get {
                return ResourceManager.GetString("UsrCtrl.ImageInfoCard.NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expanded Size: 的本地化字符串。
        /// </summary>
        public static string UsrCtrl_ImageInfoCard_SizeLabel {
            get {
                return ResourceManager.GetString("UsrCtrl.ImageInfoCard.SizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version: 的本地化字符串。
        /// </summary>
        public static string UsrCtrl_ImageInfoCard_VersionLabel {
            get {
                return ResourceManager.GetString("UsrCtrl.ImageInfoCard.VersionLabel", resourceCulture);
            }
        }
    }
}
