<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
		<TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
		<LangVersion>preview</LangVersion>
		<RootNamespace>WTGWizard</RootNamespace>
		<Nullable>enable</Nullable>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<Platforms>x64</Platforms>
		<RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
		<UseWinUI>true</UseWinUI>
		<EnableMsixTooling>true</EnableMsixTooling>
		<WindowsPackageType>None</WindowsPackageType>
		<!-- <DefineConstants>DISABLE_XAML_GENERATED_MAIN</DefineConstants> -->
	</PropertyGroup>

	<PropertyGroup>
		<ApplicationIcon>Assets\AppLogo.ico</ApplicationIcon>
	</PropertyGroup>

	<ItemGroup>
		<Manifest Include="$(ApplicationManifest)" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
		<PackageReference Include="CommunityToolkit.WinUI.Controls.Primitives" Version="8.2.251219" />
		<PackageReference Include="CommunityToolkit.WinUI.Controls.SettingsControls" Version="8.2.251219" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
		<PackageReference Include="Microsoft.WindowsAppSDK" Version="2.3.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\WTGWizard.Shared.Services\WTGWizard.Shared.Services.csproj" />
		<ProjectReference Include="..\WTGWizard.Shared.Common\WTGWizard.Shared.Common.csproj" />
		<ProjectReference Include="..\WTGWizard.Main.Language\WTGWizard.Main.Language.csproj" />
		<ProjectReference Include="..\WTGWizard.Main.DeploymentCore\WTGWizard.Main.DeploymentCore.csproj" />
	</ItemGroup>

  <ItemGroup>
    <Content Include="Assets\WinLogo\*.png" />
    <None Include="Native\x64\libwim-15.dll" CopyToOutputDirectory="PreserveNewest" Visible="false" />
  </ItemGroup>

	<Target Name="CopyWorkerOutput" AfterTargets="Build">
		<PropertyGroup>
			<WorkerOutputPath>$(MSBuildProjectDirectory)\..\WTGWizard.Worker\bin\$(Platform)\$(Configuration)\$(TargetFramework)</WorkerOutputPath>
		</PropertyGroup>
		<ItemGroup>
			<WorkerOutputFiles Include="$(WorkerOutputPath)\WTGWizard.Worker*" />
		</ItemGroup>
		<Copy SourceFiles="@(WorkerOutputFiles)" DestinationFolder="$(OutputPath)" SkipUnchangedFiles="true" />
	</Target>

	<Target Name="CopyWorkerOutputToPublish" AfterTargets="Publish">
		<PropertyGroup>
			<WorkerOutputPath>$(MSBuildProjectDirectory)\..\WTGWizard.Worker\bin\$(Platform)\$(Configuration)\$(TargetFramework)</WorkerOutputPath>
		</PropertyGroup>
		<ItemGroup>
			<WorkerOutputFiles Include="$(WorkerOutputPath)\WTGWizard.Worker*" />
		</ItemGroup>
		<Copy SourceFiles="@(WorkerOutputFiles)" DestinationFolder="$(PublishDir)" SkipUnchangedFiles="true" />
	</Target>

</Project>
