name: Build WTGWizard (manual)

on:
  workflow_dispatch:

jobs:
  run-dotnet-build:
    strategy:
      matrix:
        build-mode: [FDD, SCD]
    uses: ./.github/workflows/dotnet-build.yml
    secrets: inherit
    with:
      build-mode: ${{ matrix.build-mode }}
      upload-artifact: true
      upload-tag: Manual-Build-${{ github.run_id }}-${{ matrix.build-mode }}
      diagnostics: true
