name: Build WTGWizard (manual)

on:
  workflow_dispatch:

jobs:
  run-dotnet-build:
    uses: ./.github/workflows/dotnet-build.yml
    secrets: inherit
    with:
      is-prerelease: true
      upload-artifact: true
      publish-artifact: false
      upload-tag: Manual-Build-${{ github.run_id }}
      diagnostics: true
# this remark is intented to make the workflow show in Github Actions.
