name: Build WTGWizard (CI)

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - 'assets/*'
      - 'docs/*'
      - '.git*'

jobs:
  run-dotnet-build:
    strategy:
      matrix:
        build-mode: [FDD, SCD]
    uses: ./.github/workflows/dotnet-build.yml
    secrets: inherit
    with:
      build-mode: ${{ matrix.build-mode }}
      upload-artifact: true
      diagnostics: true
