name: Build WTGWizard (CI)

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - 'assets/*'
      - 'docs/*'
      - '.git*'

jobs:
  run-dotnet-build:
    uses: ./.github/workflows/dotnet-build.yml
    secrets: inherit
    with:
      upload-artifact: false
